Repository wecode-bootcamp-korea/18-2nd-class200ok-backend, pull requests merged in 2021-04, with the labels that each got.

#7 [안다민] (urgent) 모델 수정(추가 수정 요청 완료)
  lecture/migrations/0003_auto_20210402_0818.py
  user/migrations/0002_auto_20210402_0818.py
  user/models.py
Labels: Status: 리뷰 요청

#6 [이왕록] RDS_setting
  class200ok/settings.py
Labels: Status: Accepted

#8 [안다민] 모델링 image url 들 디폴트값 수정 (urgent)
  lecture/migrations/0004_auto_20210402_0858.py
  lecture/models.py
  user/migrations/0003_user_kakao_id.py
  user/models.py
Labels: Status: Accepted

#9 [안다민] models.py 패스워드 챠필드 값 수정(urgent)
  user/migrations/0003_auto_20210404_0525.py
  user/models.py
Labels: Status: Accepted

#14 [이왕록][긴급] 리베이스 & 데이터베이스 업로드
  db_upload.py
  lecture/migrations/0001_initial.py
  lecture/migrations/0002_auto_20210406_1401.py
  lecture/migrations/0003_auto_20210406_1449.py
  lecture/models.py
  my_settings.py.zip
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210406_1401.py
  user/migrations/0003_auto_20210406_1449.py
Labels: Status: 리뷰 요청

#15 [이왕록][긴급] 1071 에러 수정사항 unique together 해제
  lecture/models.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#17 [이왕록][긴급] CharField 크기 수정
  lecture/migrations/0004_auto_20210406_1626.py
  lecture/models.py
Labels: Status: 리뷰 요청

#20 [이왕록][긴급]Feature/models debugged
  lecture/migrations/0001_initial.py
  lecture/migrations/0002_auto_20210406_1401.py
  lecture/migrations/0003_auto_20210406_1449.py
  lecture/migrations/0004_auto_20210406_1626.py
  lecture/models.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210406_1401.py
  user/migrations/0003_auto_20210406_1449.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#21 [이왕록][긴급]Feature/pending lectures edit
  lecture/migrations/0002_auto_20210406_2150.py
  lecture/models.py
Labels: Status: 리뷰 요청

#19 [안다민] 카카오 소셜 로그인 및 데코레이터 구축(unittest 완료)
  user/tests.py
  user/urls.py
  user/views.py
  utils/decorators.py
Labels: Status: 리뷰 요청

#24 [안다민] 소셜로그인 views.py '/' 제거(conflict 해결)
  user/views.py
Labels: Status: 리뷰 요청

#26 [안다민][urgent] 데코레이터 변수명 수정
  utils/decorators.py
Labels: Status: 리뷰 요청

#22 [18기 한지영] 강좌 리스트 뷰, 필터링 구현 완료+리뷰수정 (+ unittest 완료)
  .vscode/settings.json
  lecture/0001_initial.py
  lecture/models.py
  lecture/tests.py
  lecture/urls.py
  lecture/views.py
Labels: Status: 리뷰 요청

#27 [안다민] 크리에이터 지원 기본정보 view, test 구현(유닛테스트 완료)+추가수정 완료
  class200ok/settings.py
  creator/tests.py
  creator/urls.py
  creator/views.py
Labels: Status: 리뷰 요청

#30 [이왕록]creator views & decorator added & possible exceptions added
  creator/urls.py
  creator/views.py
Labels: Status: 리뷰 요청

#29 [18기 한지영] 강좌 디테일 뷰(모달창) 구현 완료 (+unittest 완료)
  lecture/tests.py
  lecture/urls.py
  lecture/views.py
Labels: Status: Accepted

#31 [이왕록]delete description on introduction
  creator/views.py
Labels: Status: 리뷰 요청

#32 [안다민] creator views.py user null 되는 것 변경
  creator/views.py
Labels: Status: 리뷰 요청
